# Generated by Django 6.0.5 on 2026-05-28 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('assignee', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(blank=True, choices=[('К выполнению', 'К выполнению'), ('В работе', 'В работе'), ('Готово', 'Готово')], default='', max_length=50)),
            ],
        ),
    ]
