# Generated by Django 6.0.5 on 2026-06-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0003_geoobject_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('orientation', models.CharField(choices=[('Север', 'Север'), ('Юг', 'Юг'), ('Восток', 'Восток'), ('Запад', 'Запад'), ('Северо-Восток', 'Северо-Восток'), ('Северо-Запад', 'Северо-Запад'), ('Юго-Восток', 'Юго-Восток'), ('Юго-Запад', 'Юго-Запад')], max_length=50)),
                ('material', models.CharField(choices=[('Дерево', 'Дерево'), ('Металл', 'Металл'), ('ПВХ', 'ПВХ'), ('Утепленная', 'Утепленная')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='measures.building')),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('orientation', models.CharField(choices=[('Север', 'Север'), ('Юг', 'Юг'), ('Восток', 'Восток'), ('Запад', 'Запад'), ('Северо-Восток', 'Северо-Восток'), ('Северо-Запад', 'Северо-Запад'), ('Юго-Восток', 'Юго-Восток'), ('Юго-Запад', 'Юго-Запад')], max_length=50)),
                ('material', models.CharField(choices=[('ПВХ', 'ПВХ'), ('Дерево', 'Дерево'), ('Алюминий', 'Алюминий')], max_length=50)),
                ('glazing', models.CharField(choices=[('Одинарное', 'Одинарное'), ('Двойное', 'Двойное'), ('Тройное', 'Тройное'), ('Двойное энергосберегающее', 'Двойное энергосберегающее')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='measures.building')),
            ],
        ),
    ]
