# Generated by Django 6.0.5 on 2026-06-25 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0004_door_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основная секция', max_length=255)),
                ('floors', models.IntegerField(default=1)),
                ('height_outer', models.FloatField(default=3.5)),
                ('height_inner', models.FloatField(default=3.0)),
                ('wall_material', models.CharField(default='Кирпич', max_length=100)),
                ('roof_type', models.CharField(default='Плоская', max_length=100)),
                ('roof_material', models.CharField(default='Рулонная кровля', max_length=100)),
                ('length', models.FloatField(default=10.0)),
                ('width', models.FloatField(default=10.0)),
                ('offset_x', models.FloatField(default=0.0)),
                ('offset_y', models.FloatField(default=0.0)),
                ('sides', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='measures.building')),
            ],
        ),
    ]
